services:
  - type: web
    name: emotion-detector
    env: python
    pythonVersion: 3.10
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: PORT
        value: 10000  # o deja vacío para que Render asigne automáticamente
